### ISSUE TITLE
Could you provide a gene list that contained in "selected_genes_10" and "selected_genes_20"?

### ISSUE THREAD

**Issue by kimmo1019** [drugilsberg/paccmann#4]
I want to implement paccmann with custom data. 
I noticed that you used a PPI network for filtering genes, resulting in 1121 genes for "selected genes_10" and 2128 genes for "selected_genes_20". 
Could you directly provide the gene list? 
Thanks

**Comment by jannisborn** [comment]
Thanks for your interest in our work. In the [paper](https://arxiv.org/pdf/1904.11223.pdf) you find a [link](https://ibm.biz/paccmann-data) to a publicly accessible data repository where we provide all data necessary to reproduce the experiments (including your file of interest).

For brevity, click [here](https://ibm.ent.box.com/s/vfehvfly7mi2obvaj86pjuy9a82e8nik/file/489488390168) to get directly to the list of the 2128 selected genes following the network propagation over STRING. For all experiments described in the paper we use this subset and not "selected_genes_10".

Hope this helps.
Cheers, 
Jannis
