### ISSUE TITLE
How can I run paccmann with my own data?

### ISSUE THREAD

**Issue by kimmo1019** [drugilsberg/paccmann#5]
I want to run paccmann with my own data.
After I read the source code. It looks like I have to generate training and testing tfrecords data by myself. I referred to the provided example data and datasets.py. 
The tfrecords contains so many feature (fingerpirnts, targets,...etc). Do I have to generate the tfrecords data containing all the features?
e.g. I only have gene expression data, drug data(smiles) and IC50, is it right that I should only need to generate tfrecords with 3 types of features: selected_genes_20, smiles_atom_tokens and ic50?
Another question is that could you provide a detailed description for the features contained in tfrecords? I have no idea how the smiles_atom_tokens is generated, it seems smiles sequence is encoded into a 155 dimensional and vector. 
It would be better if you can provide a script for generate tfrecords.
Thanks so much!

**Comment by drugilsberg** [comment]
Hi @kimmo1019,

sorry I was away and with limited network access.

I will try to reply to you questions point by point.

> The tfrecords contains so many feature (fingerpirnts, targets,...etc). Do I have to generate the tfrecords data containing all the features?

You don't have to include all the features in the tfrecords but only the ones you plan to use.

> e.g. I only have gene expression data, drug data(smiles) and IC50, is it right that I should only need to generate tfrecords with 3 types of features: selected_genes_20, smiles_atom_tokens and ic50?

Correct.

> Another question is that could you provide a detailed description for the features contained in tfrecords? I have no idea how the smiles_atom_tokens is generated, it seems smiles sequence is encoded into a 155 dimensional and vector.

Thanks for the suggestion, I will keep the issue open and find time to work on documenting this. In the meantime regarding the smiles, the 155 dimensional vector that we are using right now is the tokenized indexes of the SMILES. In case you want to retrain you just have to provide indexes consistent with your vocabulary. We cite in our paper the regex we used to generate the tokens in case you want to follow the same procedure (https://arxiv.org/abs/1904.11223).

> It would be better if you can provide a script for generate tfrecords.

As above I will keep the issue open and notify here as soon as we have time to add this.

Hope this helps.

**Comment by Pascal-Iv** [comment]
I also have difficulties to generate the tfrecords for my data. I just want to train different folds, therefore I extracted the features from your tfrecords. Now , like @kimmo1019, I am having problems when creating the tfrecords for my folds. It would be great if you could show how you serialized the data. I was following this [tutorial](https://www.tensorflow.org/tutorials/load_data/tfrecord) from the TensorFlow docs, but this does not work for this case since the features are arrays and not scalar. I think adding a little information about this would improve the usability of your library, since there are not so many TensorFlow experts amongst us biologists yet. (Maybe also see my [StackOverflow question.)](https://stackoverflow.com/questions/59968166/python-tensorflow-creating-tfrecord-with-multiple-array-features)

Thanks!

**Comment by jannisborn** [comment]
Hey @Pascal-Iv, thanks for your interest in our work. Have you checked the versioning of the libraries you're using? Have a look at our `requirements.txt`, e.g. we use tensorflow 1.5, not 2.X, so the latter may cause problems.

**Comment by Pascal-Iv** [comment]
@jannisborn Thank you very much for your reply, yes I had the wrong version. I finally managed to store the data as tfrecords only to now get InvalidArgumentError: "Key: selected_genes_20.  Can't parse serialized Example." when trying to train on them. You probably have a script with which you store the folds as tfrecords. Would you be able to share that?


This is the code I am using to store example data as tfrecords file. Paccmann cannot parse the resulting records and I do not understand what would be the right way to store it or how to find out.
```
import numpy as np
import tensorflow as tf

# some random data
x = np.random.randn(85)
y = np.random.randn(85,2128)
z = np.random.choice(range(10),(85,155))

def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value.flatten()))

def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""

    return tf.train.Feature(int64_list=tf.train.Int64List(value=value.flatten()))

def serialize_example(feature0, feature1, feature2):
    """
    Creates a tf.Example message ready to be written to a file.
    """
    # Create a dictionary mapping the feature name to the tf.Example-compatible
    # data type.
    feature = {
      'ic50': _float_feature(feature0),
      'selected_genes_20': _float_feature(feature1),
      'smiles_atom_tokens': _int64_feature(feature2)
    }
    # Create a Features message using tf.train.Example.
    return tf.train.Example(features=tf.train.Features(feature=feature))


writer = tf.python_io.TFRecordWriter('TEST.tfrecords')
example = serialize_example(x,y,z)
writer.write(example.SerializeToString())
writer.close()
```

**Comment by jannisborn** [comment]
Dear @Pascal-Iv,

There's several problems with your code, I'm pasting below the fixed snippet:

```
import numpy as np
import tensorflow as tf

# some random data
x = np.random.randn(85,1)
y = np.random.randn(85,2128)
z = np.random.choice(range(10),(85,155))

def _float_feature(value):
    """Returns a float_list from a float / double."""
    if len(value.shape) == 1:
        value = value.reshape(-1)

    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""

    if len(value.shape) == 1:
        value = value.reshape(-1)

    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))



def serialize_example(feature0, feature1, feature2):
    """
    Creates a tf.Example message ready to be written to a file.
    """
    # Create a dictionary mapping the feature name to the tf.Example-compatible
    # data type.
    feature = {
      'selected_genes_20': _float_feature(feature1),
      'smiles_atom_tokens': _int64_feature(feature2),
      'ic50': _float_feature(feature0)
    }
    # Create a Features message using tf.train.Example.
    return tf.train.Example(features=tf.train.Features(feature=feature))


writer = tf.python_io.TFRecordWriter('TEST.tfrecords')

for xx,yy,zz in zip(x,y,z):
    example = serialize_example(xx,yy,zz)
    writer.write(example.SerializeToString())
writer.close()

```

The function is called `serialize_example` for the reason that it serializes a single example. Sounds obvious no :D
But you squeeze all data (i.e. 85 samples in your case) into a single TFRecords.
Instead, loop over all samples of your batch and write one example at a time. For that, you need to adapt the size of the labels (`x`). Then, the `.flatten()` also becomes obsolete.


In general, please note that we are not expanding this code anymore. We have migrated the entire project to PyTorch, so for the future we strongly advise to utilize the PyTorch implementation. Especially if you're not a trained computer scientist, PyTorch is easier to use, you don't need to deal TFRecords, no lacking eager execution in TF 1.X etc.

All the code for the project is [here](https://github.com/PaccMann), the code for the IC50 prediction model is [here](https://github.com/PaccMann/paccmann_predictor).
Also we released a library called `pytoda` (see [here](https://github.com/PaccMann/paccmann_datasets)) which has abstract implementations for various types of torch datasets, including Drug_Sensitivity_Dataset, SMILES_Dataset and others. If you're interested you can e.g. explore different variants of SMILES language, like excluding chirality, or other forms of stereochemistry or making bonds or hydrogens explicit.

**Comment by Pascal-Iv** [comment]
Great, this works for me! Thank you for the detailed answer and for fixing the code. I will look into the PyTorch implementation as well. I was not aware of it.
